name: Checkout Code Called Workflow

on:
  workflow_call:
    outputs:
      repo-path:
        description: "Path where the code is checked out"
        value: ${{ jobs.checkout.outputs.repo-path }}

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ github.workspace }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Verify Files After Checkout
        run: ls -la ${{ github.workspace }}
      - name: Print Repository Path Variable (`repo-path`)
        run: |
          echo "Repo Path Variable: ${{ job.checkout.outputs.repo-path }}"
