name: Main Workflow

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  checkout-code:
    uses: vcjain/github-actions/.github/workflows/checkout.yml@main

  run-sonarqube:
    needs: checkout-code
    uses: vcjain/github-actions/.github/workflows/sonarqube.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
