name: SonarQube Called Workflow

on:
  workflow_call:
    inputs:
      repo-path:
        description: "Path where the code is checked out"
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Repo Path Before Running SonarQube
        run: |
          echo "Checking repo path: ${{ inputs.repo-path }}"
          ls -la ${{ inputs.repo-path }} 
      - name: Change to Repository Directory
        run: cd ${{ inputs.repo-path }} && ls -la

      - name: Run SonarQube Scanner
        working-directory: ${{ inputs.repo-path }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=sonardemo \
            -Dsonar.organization=abc \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
