name: Test Demo1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: lab1  # 👈 Targets your specific self-hosted runner with label 'lab'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java
        run: sudo apt-get update
